import {Metadata} from "next";

export const metadata: Metadata = {
  title: {
    default: "Starting Next Js Learning",
    template: "%s | Buy High",

  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
         
        <header
        style={{
          backgroundColor: "lightblue",
          padding: "1rem"
        }}
        ><p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Laborum perferendis at corporis in nihil,</p></header>


        {children}

        <footer
        style={{
          backgroundColor: "ghostwhite",
          padding: "1rem"
        }}
        ><p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aperiam, asperiores reprehenderit veritatis deleniti expedita laudantium.</p></footer>
        
        </body>
    </html>
  )
}
 